{
 "title": "Hammerspace System Dashboard 20250905_100220",
 "tags": [
  "Hammerspace",
  "operations",
  "storage",
  "performance"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": "label_values(cluster)" },
   { "name": "step", "label": "Step", "query": "1m,5m,10m,60m" },
   {
    "name": "time_span",
    "label": "Time Span",
    "query": "1m : 2m:1m,5m : 6m:5m,10m : 11m:10m,60m : 61m:60m"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# ${cluster}" } },
  {
   "title": "Client & Protocol",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOPS Filesystem By Operation",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum by(op) (rate(hammerspace_nfs_protocol_ops{cluster='${cluster}',servicer='filesystem',op=~'getattr|setattr|read|write|open|close|access|lookup|remove|layoutget|layoutreturn|layouterror'}[$step]))",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "Latency Filesystem By Operation",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum by(op) (rate(hammerspace_nfs_protocol_ops_nanosec{cluster='${cluster}',servicer='filesystem',op=~'getattr|setattr|read|write|open|close|access|lookup|remove|layoutget|layoutreturn|layouterror'}[$step])) / sum by(op) (rate(hammerspace_nfs_protocol_ops{cluster='${cluster}',servicer='protocol',op=~'getattr|setattr|read|write|open|close|access|lookup|remove|layoutget|layoutreturn|layouterror'}[$step]))",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "IOPS Protocol By Operation",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum by(op) (rate(hammerspace_nfs_protocol_ops{cluster='${cluster}',servicer='protocol',op=~'getattr|setattr|read|write|open|close|access|lookup|remove|layoutget|layoutreturn|layouterror'}[$step]))",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "Latency Protocol By Operation",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum by(op) (rate(hammerspace_nfs_protocol_ops_nanosec{cluster='${cluster}',servicer='protocol',op=~'getattr|setattr|read|write|open|close|access|lookup|remove|layoutget|layoutreturn|layouterror'}[$step])) / sum by(op) (rate(hammerspace_nfs_protocol_ops{cluster='${cluster}',servicer='protocol',op=~'getattr|setattr|read|write|open|close|access|lookup|remove|layoutget|layoutreturn|layouterror'}[$step]))",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "DSX NFS File Read IOPS by Node",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum by(node_id) (label_replace(rate(node_nfs_requests_total{cluster='${cluster}',node_type='dsx',method='Read'}[${step}]), 'node_id', '$1', 'instance', '([^.]+).*'))",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "DSX NFS File Write IOPS by Node",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum by(node_id) (label_replace(rate(node_nfs_requests_total{cluster='${cluster}',node_type='dsx',method='Write'}[${step}]), 'node_id', '$1', 'instance', '([^.]+).*'))",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "DSX NFS Layout IOPS by Node",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum by(node_id) (label_replace(rate(node_nfs_requests_total{cluster='${cluster}',node_type='dsx',method=~'.*Layout.*'}[${step}]), 'node_id', '$1', 'instance', '([^.]+).*'))",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "DSX NFS Stat IOPS by Node",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "sum by(node_id) (label_replace(rate(node_nfs_requests_total{cluster='${cluster}',node_type='dsx',method=~'.*Stat.*'}[${step}]), 'node_id', '$1', 'instance', '([^.]+).*'))",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "Anvil NFS IOPS by Type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sum by(method) (rate(node_nfs_requests_total{cluster='${cluster}',node_type='anvil',method=~'(Access|Lookup|Remove|Rename|Close|Open|OpenNoattr|Getattr|SetAttr)'}[${step}]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "NFS IOPS by Version",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "sum by(proto) (rate(node_nfs_requests_total{cluster='${cluster}'}[${step}]))",
       "legendFormat": "{{proto}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Capacity by Share",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (volume) (label_replace(node_filesystem_size_bytes{cluster='${cluster}',fstype='nfs4',mountpoint=~'/hs/.*',node_type='anvil'} - node_filesystem_free_bytes{cluster='${cluster}',fstype='nfs4',mountpoint=~'/hs/.*',node_type='anvil'}, 'volume', '$1', 'device', '[^:]*:(.*)$')) > 0",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Inode Count by Share",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "sum by (volume) (label_replace(node_filesystem_files{cluster='${cluster}',fstype='nfs4',mountpoint=~'/hs/.*',node_type='anvil'} - node_filesystem_files_free{cluster='${cluster}',fstype='nfs4',mountpoint=~'/hs/.*',node_type='anvil'}, 'volume', '$1', 'device', '[^:]*:(.*)$')) > 0",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Capacity Change by Share",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (volume) (-label_replace(deriv(avg_over_time(node_filesystem_free_bytes{cluster='${cluster}',fstype='nfs4',mountpoint=~'/hs/.*',node_type='anvil'}[2m])[6m:5m]), 'volume', '$1', 'device', '[^:]*:(.*)$'))*300",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Inode Count Change by Share",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "sum by (volume) (-label_replace(deriv(avg_over_time(node_filesystem_files_free{cluster='${cluster}',fstype='nfs4',mountpoint=~'/hs/.*',node_type='anvil'}[2m])[6m:5m]), 'volume', '$1', 'device', '[^:]*:(.*)$'))*300",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Capacity Change by Volume/System",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (volume) (-label_replace(deriv(avg_over_time(node_filesystem_free_bytes{cluster='${cluster}',fstype='nfs4',mountpoint!~'/hs/.*',device=~'.*:/.*',node_type='anvil'}[2m])[6m:5m]), 'volume', '$1', 'device', '([^:]*):(.*)$'))*300",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Inode Count Change by Volume/System",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "sum by (volume) (-label_replace(deriv(avg_over_time(node_filesystem_files_free{cluster='${cluster}',fstype='nfs4',mountpoint!~'/hs/.*',device=~'.*:/.*',node_type='anvil'}[2m])[6m:5m]), 'volume', '$1', 'device', '([^:]*):(.*)$'))*300",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "DSX Capacity % Utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum by (node_id) (label_replace((node_filesystem_size_bytes{cluster='${cluster}',fstype='xfs',node_type='dsx',mountpoint=~'/(pd|hsvol).*'} - node_filesystem_free_bytes{cluster='${cluster}',fstype='xfs',node_type='dsx',mountpoint=~'/(pd|hsvol).*'}) / node_filesystem_size_bytes{cluster='${cluster}',fstype='xfs',node_type='dsx',mountpoint=~'/(pd|hsvol).*'}, 'node_id', '$1', 'instance', '([^.]+).*')) * 100",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "Capacity Volume % Utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "avg by (volume) (label_replace((node_filesystem_size_bytes{cluster='${cluster}',fstype='nfs4',node_type='anvil',mountpoint!~'/hs/.*',device=~'.*:/.*'} - node_filesystem_free_bytes{cluster='${cluster}',fstype='nfs4',node_type='anvil',mountpoint!~'/hs/.*',device=~'.*:/.*'}) / node_filesystem_size_bytes{cluster='${cluster}',fstype='nfs4',node_type='anvil',mountpoint!~'/hs/.*',device=~'.*:/.*'}, 'volume', '$1', 'device', '(.*)')) * 100",
       "legendFormat": "{{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Anvil CPU %",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - avg by (node_id) (label_replace(rate(node_cpu_seconds_total{cluster='${cluster}',mode='idle',node_type='anvil'}[${step}]),'node_id','$1','instance','([^.]+).*'))) * 100 > 0",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "DSX CPU %",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - avg by (node_id) (label_replace(rate(node_cpu_seconds_total{cluster='${cluster}',mode='idle',node_type='dsx'}[${step}]),'node_id','$1','instance','([^.]+).*'))) * 100 > 0",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "Anvil Network Throughput In (Receive)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (node_id) (label_replace(rate(node_network_receive_bytes_total{cluster='${cluster}',node_type='anvil'}[$step]),'node_id','$1','instance','([^.]+).*'))",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "DSX Network Throughput In (Receive)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (node_id) (label_replace(rate(node_network_receive_bytes_total{cluster='${cluster}',node_type='dsx'}[$step]),'node_id','$1','instance','([^.]+).*'))",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "Anvil Network Throughput Out (Transmit)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (node_id) (label_replace(rate(node_network_transmit_bytes_total{cluster='${cluster}',node_type='anvil'}[$step]),'node_id','$1','instance','([^.]+).*'))",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "DSX Network Throughput Out (Transmit)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (node_id) (label_replace(rate(node_network_transmit_bytes_total{cluster='${cluster}',node_type='dsx'}[$step]),'node_id','$1','instance','([^.]+).*'))",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "Anvil Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (node_id) (label_replace(node_memory_MemTotal_bytes{cluster='${cluster}',node_type='anvil'}-node_memory_MemAvailable_bytes{cluster='${cluster}',node_type='anvil'},'node_id','$1','instance','([^.]+).*'))",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "DSX Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (node_id) (label_replace(node_memory_MemTotal_bytes{cluster='${cluster}',node_type='dsx'}-node_memory_MemAvailable_bytes{cluster='${cluster}',node_type='dsx'},'node_id','$1','instance','([^.]+).*'))",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "CPU by Services Group",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (service) (rate(hammerspace_services_cg_cpu_ns{cluster='${cluster}'}[$step]) / 1000000000)",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Uptime HW, via Networking",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (node_id) (label_replace(node_network_receive_bytes_total{cluster='${cluster}'}, 'node_id', '$1', 'instance', '([^.]+).*'))",
       "legendFormat": "{{node_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DSX Drives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Read Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (device_type) (label_replace(rate(node_disk_read_time_seconds_total{cluster='${cluster}',node_type='dsx'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*')) / sum by (device_type) (label_replace(rate(node_disk_reads_completed_total{cluster='${cluster}',node_type='dsx'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*'))",
       "legendFormat": "{{device_type}}"
      }
     ]
    },
    {
     "title": "Disk Read Throughput",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (device_type) (label_replace(rate(node_disk_read_bytes_total{cluster='${cluster}',node_type='dsx'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*'))",
       "legendFormat": "{{device_type}}"
      }
     ]
    },
    {
     "title": "Disk Read Size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (device_type) (label_replace(rate(node_disk_read_bytes_total{cluster='${cluster}',node_type='dsx'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*'  )) / sum by (device_type) (label_replace(rate(node_disk_reads_completed_total{cluster='${cluster}',node_type='dsx'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*'  ))",
       "legendFormat": "{{device_type}}"
      }
     ]
    },
    {
     "title": "Disk Read OPS",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "sum by (device_type) (label_replace(rate(node_disk_reads_completed_total{cluster='${cluster}',node_type='dsx'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*'))",
       "legendFormat": "{{device_type}}"
      }
     ]
    },
    {
     "title": "Disk Write Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (device_type) (label_replace(rate(node_disk_write_time_seconds_total{cluster='${cluster}',node_type='dsx'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*')) / sum by (device_type) (label_replace(rate(node_disk_writes_completed_total{cluster='${cluster}',node_type='dsx'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*'))",
       "legendFormat": "{{device_type}}"
      }
     ]
    },
    {
     "title": "Disk Write Throughput",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (device_type) (label_replace(rate(node_disk_written_bytes_total{cluster='${cluster}',node_type='dsx'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*'))",
       "legendFormat": "{{device_type}}"
      }
     ]
    },
    {
     "title": "Disk Write Size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (device_type) (label_replace(rate(node_disk_written_bytes_total{cluster='${cluster}',node_type='dsx'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*'  )) / sum by (device_type) (label_replace(rate(node_disk_writes_completed_total{cluster='${cluster}',node_type='dsx'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*'  ))",
       "legendFormat": "{{device_type}}"
      }
     ]
    },
    {
     "title": "Disk Write OPS",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "sum by (device_type) (label_replace(rate(node_disk_writes_completed_total{cluster='${cluster}',node_type='dsx'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*'))",
       "legendFormat": "{{device_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Anvil Drives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Read Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (device_type) (label_replace(rate(node_disk_read_time_seconds_total{cluster='${cluster}',node_type='anvil'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*')) / sum by (device_type) (label_replace(rate(node_disk_reads_completed_total{node_type='anvil'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*'))",
       "legendFormat": "{{device_type}}"
      }
     ]
    },
    {
     "title": "Disk Read Throughput",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (device_type) (label_replace(rate(node_disk_read_bytes_total{cluster='${cluster}',node_type='anvil'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*'))",
       "legendFormat": "{{device_type}}"
      }
     ]
    },
    {
     "title": "Disk Read Size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (device_type) (label_replace(rate(node_disk_read_bytes_total{cluster='${cluster}',node_type='anvil'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*'  )) / sum by (device_type) (label_replace(rate(node_disk_reads_completed_total{cluster='${cluster}',node_type='anvil'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*'  ))",
       "legendFormat": "{{device_type}}"
      }
     ]
    },
    {
     "title": "Disk Read OPS",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum by (device_type) (label_replace(rate(node_disk_reads_completed_total{cluster='${cluster}',node_type='anvil'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*'))",
       "legendFormat": "{{device_type}}"
      }
     ]
    },
    {
     "title": "Disk Write Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (device_type) (label_replace(rate(node_disk_write_time_seconds_total{cluster='${cluster}',node_type='anvil'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*')) / sum by (device_type) (label_replace(rate(node_disk_writes_completed_total{cluster='${cluster}',node_type='anvil'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*'))",
       "legendFormat": "{{device_type}}"
      }
     ]
    },
    {
     "title": "Disk Write Throughput",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (device_type) (label_replace(rate(node_disk_written_bytes_total{cluster='${cluster}',node_type='anvil'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*'))",
       "legendFormat": "{{device_type}}"
      }
     ]
    },
    {
     "title": "Disk Write Size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (device_type) (label_replace(rate(node_disk_written_bytes_total{cluster='${cluster}',node_type='anvil'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*'  )) / sum by (device_type) (label_replace(rate(node_disk_writes_completed_total{cluster='${cluster}',node_type='anvil'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*'  ))",
       "legendFormat": "{{device_type}}"
      }
     ]
    },
    {
     "title": "Disk Write OPS",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "sum by (device_type) (label_replace(rate(node_disk_writes_completed_total{cluster='${cluster}',node_type='anvil'}[$step]), 'device_type', '$1', 'device', '(nvme|sd|md|[a-z]{2}).*'))",
       "legendFormat": "{{device_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFS Errors by type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum by(err) (increase(hammerspace_nfs_protocol_server_errors_by_share{cluster='${cluster}'}[$step]))  > 0",
       "legendFormat": "{{err}}"
      }
     ]
    },
    {
     "title": "NFS Errors by share",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "topk(10, sum_over_time(sum by(share) (increase(hammerspace_nfs_protocol_server_errors_by_share{cluster='${cluster}'}[$step]))[${time_span}]))",
       "legendFormat": "{{share}}"
      }
     ]
    },
    {
     "title": "NFS Errors by client",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "topk(10, sum_over_time(sum by(client_ip) (increase(hammerspace_nfs_protocol_server_errors_by_client{cluster='${cluster}'}[$step]))[${time_span}]))",
       "legendFormat": "{{client_ip}}"
      }
     ]
    },
    {
     "title": "Layout Errors by Type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sum by(err) (increase(hammerspace_nfs_protocol_layout_errors_by_volume{cluster='${cluster}'}[$step]))  > 0",
       "legendFormat": "{{err}}"
      }
     ]
    },
    {
     "title": "Layout Errors by volume",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum by(volume) (rate(hammerspace_nfs_protocol_layout_errors_by_volume{}[$step]))  > 0",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "EDAC Uncorrectable Errors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "sum by(node_id) (label_replace(increase(node_edac_csrow_uncorrectable_errors_total{cluster='${cluster}'}[$step]),'node_id','$1','instance','([^.]+).*'))  > 0",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "Icmp In Errors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum by(node_id) (label_replace(increase(node_netstat_Icmp_InErrors{cluster='${cluster}'}[$step]),'node_id','$1','instance','([^.]+).*'))  > 0",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "NFS RPC Errors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "sum by(node_id) (label_replace(increase(node_nfsd_rpc_errors_total{cluster='${cluster}'}[$step]),'node_id','$1','instance','([^.]+).*'))  > 0",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "Filesystem Device Errors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "sum by(device) (increase(node_filesystem_device_errors_total{cluster='${cluster}'}[$step])) > 0",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "DME RPC Failure by Type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "expr": "sum by(rpc) (increase(hammerspace_dme_rpc_extended_count{cluster='${cluster}',status='fail'}[$step])) > 0",
       "legendFormat": "{{rpc}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hammerspace Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Send Time Behind by Site",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(from_site) (hammerspace_filesystem_replication_send_behind{cluster='${cluster}'} )",
       "legendFormat": "{{from_site}}"
      }
     ]
    },
    {
     "title": "Replication Receive Time Behind by Site",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(to_site) (hammerspace_filesystem_replication_recv_behind{cluster='${cluster}'} )",
       "legendFormat": "{{to_site}}"
      }
     ]
    },
    {
     "title": "Replication Send Complete by Site",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum by(from_site) (increase(hammerspace_filesystem_replication_send{cluster='${cluster}'}[${step}]))",
       "legendFormat": "{{from_site}}"
      }
     ]
    },
    {
     "title": "Replication Merge Recs by Share",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "sum by(share) (increase(hammerspace_filesystem_ops{cluster='${cluster}',op='replication_merge_recs'}[${step}]))",
       "legendFormat": "{{share}}"
      }
     ]
    },
    {
     "title": "Grading Files Producer Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "count" } },
     "targets": [
      {
       "expr": "sum by(producer) (increase(hammerspace_grading_files_producer_count{cluster='${cluster}'}[${step}]))",
       "legendFormat": "{{producer}}"
      }
     ]
    },
    {
     "title": "Grading Misaligned Files",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "rate(hammerspace_grading_misaligned_files_count{cluster='${cluster}'}[${step}])"
      }
     ]
    },
    {
     "title": "Mobility Actively Moving Files",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum by(status) (hammerspace_mobility_actively_moving_files{cluster='${cluster}'} )",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Mobility Jobs by Type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "sum by(msm) (increase(hammerspace_mobility_jobs_run{cluster='${cluster}'}[${step}]))",
       "legendFormat": "{{msm}}"
      }
     ]
    },
    {
     "title": "Queued for Mobility",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "hammerspace_actuary_queued_for_mobility_files{cluster='${cluster}'}"
      }
     ]
    },
    {
     "title": "Object Garbage Collection Bytes Freed",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(osv) (increase(hammerspace_cgc_session_stats_total_bytes_freed{cluster='${cluster}'}[${step}]))",
       "legendFormat": "{{osv}}"
      }
     ]
    },
    {
     "title": "DME RPC Success by Type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "sum by(rpc) (increase(hammerspace_dme_rpc_extended_count{cluster='${cluster}',status='success'}[$step]))",
       "legendFormat": "{{rpc}}"
      }
     ]
    },
    {
     "title": "DME RPC Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(rpc) (hammerspace_dme_rpc_extended_timing{cluster='${cluster}'} / 1000000000)",
       "legendFormat": "{{rpc}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hammerspace Object",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Objects Uploaded By Bucket",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum by(bkt_id) (increase(hammerspace_object_file_upload_count{cluster='${cluster}'}[$step]))",
       "legendFormat": "{{bkt_id}}"
      }
     ]
    },
    {
     "title": "Objects Downloaded By Bucket",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum by(bkt_id) (increase(hammerspace_object_file_download_count{cluster='${cluster}'}[$step]))",
       "legendFormat": "{{bkt_id}}"
      }
     ]
    },
    {
     "title": "Bytes Uploaded (Physical)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(bkt_id) (increase(hammerspace_object_bytes_uploaded_physical{cluster='${cluster}'}[$step]))",
       "legendFormat": "{{bkt_id}}"
      }
     ]
    },
    {
     "title": "Bytes Downloaded (Physical)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(bkt_id) (increase(hammerspace_object_bytes_downloaded_physical{cluster='${cluster}'}[$step]))",
       "legendFormat": "{{bkt_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Extras: Physical/Environment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Anvil Power (Watts)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "watts" } },
     "targets": [
      {
       "expr": "sum by (node_id) (label_replace(rate(node_rapl_package_joules_total{cluster='${cluster}',node_type='anvil'}[$step]), 'node_id', '$1', 'instance', '([^.]+).*'))",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "DSX Power (Watts)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "watts" } },
     "targets": [
      {
       "expr": "sum by (node_id) (label_replace(rate(node_rapl_package_joules_total{cluster='${cluster}',node_type='dsx'}[$step]), 'node_id', '$1', 'instance', '([^.]+).*'))",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "Anvil Temperature (Celsius)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (node_id) (label_replace(node_hwmon_temp_celsius{cluster='${cluster}',node_type='anvil',chip=~'platform_.*'}, 'node_id', '$1', 'instance', '([^.]+).*'))",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "DSX Temperature (Celsius)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (node_id) (label_replace(node_hwmon_temp_celsius{cluster='${cluster}',node_type='dsx',chip=~'platform_.*'}, 'node_id', '$1', 'instance', '([^.]+).*'))",
       "legendFormat": "{{node_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Extras: Client & Protocol",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFS Read Throughput by Node",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (node_id) (label_replace(rate(node_nfsd_disk_bytes_read_total{cluster='${cluster}',node_type='dsx'}[$step]), 'node_id', '$1', 'instance', '([^.]+).*'))",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "NFS Write Throughput by Node",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (node_id) (label_replace(rate(node_nfsd_disk_bytes_written_total{cluster='${cluster}',node_type='dsx'}[$step]), 'node_id', '$1', 'instance', '([^.]+).*'))",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "DSX StatFS by Share",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk(10, avg_over_time(sum by(volume) (label_replace(rate(node_mountstats_nfs_operations_received_bytes_total{cluster='${cluster}',node_type='dsx',operation='STATFS'}[$step]), 'volume', '$1', 'export', '.*:(.*)$'))[${time_span}]))",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "DSX StatFS Latency by Share",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(10, avg_over_time(sum by(volume) (label_replace(1000 * rate(node_mountstats_nfs_operations_response_time_seconds_total{cluster='${cluster}',node_type='dsx',operation='STATFS'}[$step]) / rate(node_mountstats_nfs_operations_requests_total{cluster='${cluster}',node_type='dsx',operation='STATFS'}[$step]), 'volume', '$1', 'export', '.*:(.*)$'))[${time_span}]))",
       "legendFormat": "{{volume}}"
      }
     ]
    }
   ]
  }
 ]
}