{
 "title": "Hammerspace Dashboard: Drives",
 "tags": [ "drives" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "dsx_drive_exclusion", "query": "(dm|md|sr).*" },
   { "name": "anvil_drive_exclusion", "query": "(dr|dm).*" },
   { "name": "step", "query": "10m" }
  ]
 },
 "panels": [
  {
   "title": "DSX Write Latency",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_join(\n  label_replace(\n    (\n      rate(node_disk_write_time_seconds_total{cluster='${cluster}',node_type='dsx',device!~\"${dsx_drive_exclusion}\"}[${step}])\n      /\n      rate(node_disk_writes_completed_total{cluster='${cluster}',node_type='dsx',device!~\"${dsx_drive_exclusion}\"}[${step}])\n    ),\n    \"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"\n  ), \n  \"sort_key\", \" : \", \"instance_num\", \"device\"\n)",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "DSX Write IOPS",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "label_join(\nlabel_replace(\nrate(node_disk_writes_completed_total{cluster='${cluster}',node_type='dsx',device!~\"${dsx_drive_exclusion}\"}[${step}]),\n\"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"), \"sort_key\", \" : \", \"instance_num\", \"device\"\n)",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "DSX Write Throughput",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "label_join(\nlabel_replace(\nrate(node_disk_written_bytes_total{cluster='${cluster}',node_type='dsx',device!~\"${dsx_drive_exclusion}\"}[${step}]),\n\"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"), \"sort_key\", \" : \", \"instance_num\", \"device\"\n)",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "DSX read Latency",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "label_join(\n  label_replace(\n    (\n      rate(node_disk_read_time_seconds_total{cluster='${cluster}',node_type='dsx',device!~\"${dsx_drive_exclusion}\"}[${step}])\n      /\n      rate(node_disk_reads_completed_total{cluster='${cluster}',node_type='dsx',device!~\"${dsx_drive_exclusion}\"}[${step}])\n    ),\n    \"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"\n  ), \n  \"sort_key\", \" : \", \"instance_num\", \"device\"\n)",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "DSX Read IOPS",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "label_join(\nlabel_replace(\nrate(node_disk_reads_completed_total{cluster='${cluster}',node_type='dsx',device!~\"${dsx_drive_exclusion}\"}[${step}]),\n\"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"), \"sort_key\", \" : \", \"instance_num\", \"device\"\n)",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "DSX Read Throughput",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "label_join(\nlabel_replace(\nrate(node_disk_read_bytes_total{cluster='${cluster}',node_type='dsx',device!~\"${dsx_drive_exclusion}\"}[${step}]),\n\"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"), \"sort_key\", \" : \", \"instance_num\", \"device\"\n)",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "Anvil Write Latency",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "label_join(\n    label_replace(\n      clamp_max(\n        (\n          rate(node_disk_write_time_seconds_total{cluster='${cluster}',node_type='anvil',device!~\"${anvil_drive_exclusion}\"}[${step}])\n          /\n          rate(node_disk_writes_completed_total{cluster='${cluster}',node_type='anvil',device!~\"${anvil_drive_exclusion}\"}[${step}])\n        ),\n        0.005\n      ),\n      \"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"\n    ),\n    \"sort_key\", \" : \", \"instance_num\", \"device\"\n  )",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "Anvil Write IOPS",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "label_join(\nlabel_replace(\nrate(node_disk_writes_completed_total{cluster='${cluster}',node_type='anvil',device!~\"${anvil_drive_exclusion}\"}[${step}]),\n\"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"), \"sort_key\", \" : \", \"instance_num\", \"device\"\n)",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "Anvil Write Throughput",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 150 },
   "targets": [
    {
     "expr": "label_join(\nlabel_replace(\nclamp_max(rate(node_disk_written_bytes_total{cluster='${cluster}',node_type='anvil',device!~\"${anvil_drive_exclusion}\"}[${step}]), 10000000),\n\"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"), \"sort_key\", \" : \", \"instance_num\", \"device\"\n)",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "Anvil Read Latency",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 135 },
   "targets": [
    {
     "expr": "label_join(\n    label_replace(\n      clamp_max(\n        (\n          rate(node_disk_read_time_seconds_total{cluster='${cluster}',node_type='anvil',device!~\"${anvil_drive_exclusion}\"}[${step}])\n          /\n          rate(node_disk_reads_completed_total{cluster='${cluster}',node_type='anvil',device!~\"${anvil_drive_exclusion}\"}[${step}])\n        ),\n        0.01\n      ),\n      \"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"\n    ),\n    \"sort_key\", \" : \", \"instance_num\", \"device\"\n  )",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "Anvil Read IOPS",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 150 },
   "targets": [
    {
     "expr": "label_join(\nlabel_replace(\nclamp_max(rate(node_disk_reads_completed_total{cluster='${cluster}',node_type='anvil',device!~\"${anvil_drive_exclusion}\"}[${step}]), 200),\n\"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"), \"sort_key\", \" : \", \"instance_num\", \"device\"\n)",
     "legendFormat": "{{instance_device}}"
    }
   ]
  },
  {
   "title": "Anvil Read Throughput",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 165 },
   "targets": [
    {
     "expr": "label_join(\nlabel_replace(\nclamp_max(rate(node_disk_read_bytes_total{cluster='${cluster}',node_type='anvil',device!~\"${anvil_drive_exclusion}\"}[${step}]), 2000000),\n\"instance_num\", \"$1\", \"instance\", \".*?([0-9]+)[.].*\"), \"sort_key\", \" : \", \"instance_num\", \"device\"\n)",
     "legendFormat": "{{instance_device}}"
    }
   ]
  }
 ]
}